### ISSUE TITLE
Crash sometimes when click on report.

### ISSUE THREAD

**Issue by L-A-Marchetti** [L-A-Marchetti/BOMulus#57]
```bash
Building BOMulus...
Running BOMulus...
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: closure error: unexpected panic caught: runtime error: index out of range [0] with length 0

Closure added at:
	gui.btnAnalyze at /home/lam/Documents/prototypes/BOMulus/pkg/gui/btn_analyze.go:24
	gui.filters at /home/lam/Documents/prototypes/BOMulus/pkg/gui/filters.go:28
	gui.runAnalysis.func2 at /home/lam/Documents/prototypes/BOMulus/pkg/gui/analysis.go:36

goroutine 1 [running]:
github.com/gotk3/gotk3/internal/closure.FuncStack.Panicf({{0x89d620, 0x9f0b40, 0x13}, {0xc000394618, 0x3, 0x3}}, {0x9c0b8a, 0x1b}, {0xc00003a2f0, 0x1, ...})
	/home/lam/go/pkg/mod/github.com/gotk3/gotk3@v0.6.5-0.20240618185848-ff349ae13f56/internal/closure/funcstack.go:116 +0x91e
github.com/gotk3/gotk3/internal/closure.FuncStack.TryRepanic({{0x89d620, 0x9f0b40, 0x13}, {0xc000394618, 0x3, 0x3}})
	/home/lam/go/pkg/mod/github.com/gotk3/gotk3@v0.6.5-0.20240618185848-ff349ae13f56/internal/closure/funcstack.go:134 +0x145
panic({0x9089e0?, 0xc00002a2b8?})
	/home/lam/.go/src/runtime/panic.go:770 +0x132
report.MinMaxPrice()
	/home/lam/Documents/prototypes/BOMulus/pkg/report/report.go:57 +0x2fa
gui.ShowReport()
	/home/lam/Documents/prototypes/BOMulus/pkg/gui/report.go:21 +0xa8a
gui.btnAnalyze.func1()
	/home/lam/Documents/prototypes/BOMulus/pkg/gui/btn_analyze.go:25 +0xf
reflect.Value.call({0x89d620?, 0x9f0b40?, 0xe30000000048a665?}, {0x9a9f1c, 0x4}, {0xe4ba80, 0x0, 0x8bda60?})
	/home/lam/.go/src/reflect/value.go:596 +0xca6
reflect.Value.Call({0x89d620?, 0x9f0b40?, 0x173c9e0?}, {0xe4ba80?, 0x8d8c40?, 0x0?})
	/home/lam/.go/src/reflect/value.go:380 +0xb9
github.com/gotk3/gotk3/glib.goMarshal(0x566700?, 0x0, 0x1, 0x7fffa7328ad0, 0x48ae25?, 0x3?)
	/home/lam/go/pkg/mod/github.com/gotk3/gotk3@v0.6.5-0.20240618185848-ff349ae13f56/glib/glib.go:271 +0xa11
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:17506 +0x3f
github.com/gotk3/gotk3/gtk.Main(...)
	/home/lam/go/pkg/mod/github.com/gotk3/gotk3@v0.6.5-0.20240618185848-ff349ae13f56/gtk/gtk.go:1243
gui.GuiInit()
	/home/lam/Documents/prototypes/BOMulus/pkg/gui/gui_init.go:46 +0x14b
main.main()
	/home/lam/Documents/prototypes/BOMulus/cmd/BOMulus/main.go:23 +0xf
make: *** [Makefile:21: run] Error 2

```

**Comment by L-A-Marchetti** [comment]
- MinMaxPrice() fixed.
